table cohort_retention
	lineageTag: 417b4873-8441-42d7-9080-fb820698fe01

	column cohort
		dataType: string
		lineageTag: f82785f9-1562-4851-bdc0-3745ea9fd124
		summarizeBy: none
		sourceColumn: cohort

		annotation SummarizationSetBy = Automatic

	column month_index
		dataType: int64
		formatString: 0
		lineageTag: 322935d2-0e21-4094-954f-3e6865882451
		summarizeBy: sum
		sourceColumn: month_index

		annotation SummarizationSetBy = Automatic

	column cohort_size
		dataType: int64
		formatString: 0
		lineageTag: 4611b92b-5908-4d9b-95ad-815b617c210f
		summarizeBy: sum
		sourceColumn: cohort_size

		annotation SummarizationSetBy = Automatic

	column active_customers
		dataType: int64
		formatString: 0
		lineageTag: 1fab2234-93a5-4b2b-8315-beb771f19c95
		summarizeBy: sum
		sourceColumn: active_customers

		annotation SummarizationSetBy = Automatic

	column retention_rate
		dataType: double
		formatString: %0.0;-%0.0;%0.0
		lineageTag: 4217a625-ce6c-4d73-8bb0-80e4d0ac8a2f
		summarizeBy: sum
		sourceColumn: retention_rate

		annotation SummarizationSetBy = Automatic

	partition cohort_retention = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Text.Combine({DataRoot, "cohort_retention.csv"}, "\")), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {
				        {"cohort", type text}, {"month_index", Int64.Type}, {"cohort_size", Int64.Type},
				        {"active_customers", Int64.Type}, {"retention_rate", type number}
				    }, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

