table dim_date
	lineageTag: 0efa38b8-3de2-4443-8054-87be49971d76
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 15227071-68c2-4f68-b954-c5faf321d707
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 90831b23-c8f5-4f2c-aa7f-796e9a7d7348
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: dd8b93dd-a2c4-44f9-8dca-ee4126d3a93a
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 902ce8c1-2f9b-4567-8dd4-55f0679652e1
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Text.Combine({DataRoot, "dim_date.csv"}, "\")), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"date", type date}, {"year", Int64.Type}, {"month", Int64.Type}, {"year_month", type text}}, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

