table dim_customer
	lineageTag: 6f09ff43-4bf0-48d3-a90c-d64c302da93f

	column customer_id
		dataType: string
		lineageTag: 17e12c12-a2ba-4f92-a5c3-b4b75c5a4f9c
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 8d159645-4947-4687-a058-e38030ed1476
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(Text.Combine({DataRoot, "dim_customer.csv"}, "\")), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"customer_id", type text}, {"country", type text}}, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

